name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.3
      - name: Build
        run: |
          pnpm i
          pnpm build
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: .output/public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
